# Generated by Django 2.2.3 on 2019-07-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0002_courseenrolled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentAuthInfo',
        ),
    ]
