# Generated by Django 2.2.3 on 2019-07-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0003_delete_studentauthinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrolled',
            old_name='studentId',
            new_name='student',
        ),
    ]
