# Generated by Django 2.2.2 on 2019-07-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.CharField(max_length=30)),
                ('date', models.DateTimeField(null=True)),
                ('announcement', models.CharField(max_length=300)),
            ],
        ),
    ]
