# Generated by Django 2.2.2 on 2019-07-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0002_auto_20190722_2334'),
        ('web', '0004_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='teacherId',
        ),
        migrations.AddField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userhandling.Users'),
            preserve_default=False,
        ),
    ]
