# Generated by Django 2.2.2 on 2019-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190728_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='teacher',
        ),
        migrations.AddField(
            model_name='announcement',
            name='teacherId',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
