# Generated by Django 2.2.2 on 2019-07-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190728_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='teacherId',
            new_name='teacher',
        ),
    ]
