# Generated by Django 2.2.3 on 2019-07-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
                ('deadline', models.DateTimeField()),
                ('totalmarks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=400)),
                ('submissiondate', models.DateTimeField()),
                ('givenmarks', models.FloatField()),
                ('feedback', models.CharField(max_length=200)),
                ('assignmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Assignments')),
            ],
        ),
    ]
