# Generated by Django 2.2.3 on 2019-07-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20190722_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Courses'),
        ),
    ]
