# Generated by Django 2.2.3 on 2019-07-22 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0003_courses'),
        ('userhandling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Courses')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhandling.Users')),
            ],
        ),
    ]
